name: drupal8-contrib
recipe: drupal8
env_file:
  - .env
config:
  webroot: ./web
  php: '7.2'
  drush: '*'
  xdebug: false
proxy:
  pma:
    - pma-d8-contrib.lndo.site
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  make:
    service: appserver
  drush:
    cmd: "/var/www/.composer/vendor/bin/drush --root=/app/web"
